#pragma once

#include <vector>
#include "opencv2\core.hpp"

class Skeleton
{

	std::vector<cv::Point> points;

public:
	Skeleton();
	~Skeleton();
};

enum class COCOSkeletonPoint
{
	NOSE = 0, NECK, RIGHT_SHOULDER, RIGHT_ELBOW, RIGHT_WRIST,
	LEFT_SHOULDER, LEFT_ELBOW, LEFT_WRIST, RIGHT_HIP,
	RIGHT_KNEE, RIGHT_ANKLE, LEFT_HIP, LEFT_KNEE,
	LEFT_ANKLE, RIGHT_EYE, LEFT_EYE, RIGHT_EAR, LEFT_EAR,
	BACKGROUND
};

enum class MPISkeletonPoint
{
	HEAD = 0, NECK, RIGHT_SHOULDER, RIGHT_ELBOW, RIGHT_WRIST,
	LEFT_SHOULDER, LEFT_ELBOW, LEFT_WRIST, RIGHT_HIP,
	RIGHT_KNEE, RIGHT_ANKLE, LEFT_HIP, LEFT_KNEE,
	LEFT_ANKLE, CHEST, BACKGROUND
};

